var someText = "﻿int totalParticles = 100;\r\nParticle[] particles = new Particle[totalParticles];\r\n\r\nfloat targetX = 0.0;\r\nfloat targetY = 0.0;\r\n\r\nint width, height;\r\n\r\nvoid setup() {\r\n    width = 480;\r\n    height = 800;\r\n    size(width, height);\r\n    noStroke();\r\n    smooth();\r\n    background(0);\r\n    for (int i = 0; i < totalParticles; i++) {\r\n        Particle particle = new Particle();\r\n        particles[i] = particle;\r\n    }\r\n};\r\n\r\nvoid draw() {\r\n    fill(color(0, 0, 0, 20));\r\n    rect(0, 0, width, height);\r\n\r\n    for (int i = 0; i < totalParticles; i++) {\r\n        particles[i].update();\r\n        particles[i].render();\r\n    }\r\n};\r\n\r\nint particleIndex = 0;\r\n\r\n\r\n//void mouseMoved(){\r\n//    targetX += (mouseX - targetX) * .2;\r\n//    targetY += (mouseY - targetY) * .2;\r\n//    Particle nextParticle = particles[particleIndex];\r\n//    nextParticle.reset(targetX, targetY);\r\n//    if (++particleIndex >= particles.length) particleIndex = 0;\r\n//}\r\n\r\nvoid pointerMove(Pointer e) {\r\n    targetX += (e.offsetX - targetX) * .2;\r\n    targetY += (e.offsetY - targetY) * .2;\r\n    var nextParticle = particles[particleIndex];\r\n    nextParticle.reset(targetX, targetY);\r\n    if (++particleIndex >= particles.length) particleIndex = 0;\r\n}\r\n\r\nclass Particle {\r\n  float x = 0.0;\r\n  float y = 0.0;\r\n  float vx = 0.0;\r\n  float vy = 0.0;\r\n  float r = 255;\r\n  float g = 255;\r\n  float b = 255;\r\n  float a = 255;\r\n  color pColor = color(255, 255, 255, 255);\r\n  int life = 0;\r\n\r\n  void update() {\r\n    if (this.life > 0) {\r\n        this.life--;\r\n        if (this.life < 50) {\r\n            this.x += this.vx;\r\n            this.y += this.vy;\r\n            this.vx += random(4) - 2;\r\n            this.vy += random(4) - 2;\r\n            this.vx *= .9;\r\n            this.vy *= .9;\r\n            this.a = 255 * (this.life / 50.0);\r\n        }\r\n    }\r\n  }\r\n  \r\n  void reset(float _x, float _y) {\r\n      this.x = _x;\r\n      this.y = _y;\r\n      this.vx = random(4) - 2;\r\n      this.vy = random(4) * 4 - 2;\r\n      this.life = 150;\r\n      this.g = map(_x, 0, width, 0, 255);\r\n      this.b = map(_y, 0, height, 0, 255);\r\n      this.a = 255;\r\n  }\r\n\r\n  void render(){\r\n      fill(color(this.r, this.g, this.b, this.a));\r\n      ellipse(this.x, this.y, 5, 5);\r\n  }\r\n}";
var canvasRoot;
canvasRoot = document.getElementById("canvasRoot");
var localSketch;
//localSketch = Processing.compile(sketchText);
//localSketch = 
//p = new Processing(canvasRoot, localSketch);
function loadSketch(sketchText) {
    localSketch = new Processing(canvasRoot, sketchText);
}

//loadSketch(someText);

window.external.notify("Javascript Ready");